# Site settings
title: GOVstrap
description: A GOV.UK based theme for Bootstrap.
baseurl: "/GOVstrap" # the subpath of your site, e.g. /blog
url: "http://matthew-shaw.github.io" # the base hostname & protocol for your site
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
    style: compressed

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
