# Site settings
title: GovStrap
description: A GOV.UK based theme for Bootstrap.
baseurl: "/GovStrap" # the subpath of your site, e.g. /blog
url: "http://matthew-shaw.github.io" # the base hostname & protocol for your site
gems:
  - jekyll-sitemap
  - jekyll-seo-tag


# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
